# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/egor/code/apps/CLion-2018.2.3/clion-2018.2.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/egor/code/apps/CLion-2018.2.3/clion-2018.2.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/egor/tsab

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/egor/tsab

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/egor/code/apps/CLion-2018.2.3/clion-2018.2.3/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/egor/code/apps/CLion-2018.2.3/clion-2018.2.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egor/tsab/CMakeFiles /home/egor/tsab/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egor/tsab/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tsab

# Build rule for target.
tsab: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsab
.PHONY : tsab

# fast build rule for target.
tsab/fast:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/build
.PHONY : tsab/fast

src/audio.o: src/audio.cpp.o

.PHONY : src/audio.o

# target to build an object file
src/audio.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/audio.cpp.o
.PHONY : src/audio.cpp.o

src/audio.i: src/audio.cpp.i

.PHONY : src/audio.i

# target to preprocess a source file
src/audio.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/audio.cpp.i
.PHONY : src/audio.cpp.i

src/audio.s: src/audio.cpp.s

.PHONY : src/audio.s

# target to generate assembly for a file
src/audio.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/audio.cpp.s
.PHONY : src/audio.cpp.s

src/fs.o: src/fs.cpp.o

.PHONY : src/fs.o

# target to build an object file
src/fs.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/fs.cpp.o
.PHONY : src/fs.cpp.o

src/fs.i: src/fs.cpp.i

.PHONY : src/fs.i

# target to preprocess a source file
src/fs.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/fs.cpp.i
.PHONY : src/fs.cpp.i

src/fs.s: src/fs.cpp.s

.PHONY : src/fs.s

# target to generate assembly for a file
src/fs.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/fs.cpp.s
.PHONY : src/fs.cpp.s

src/graphics.o: src/graphics.cpp.o

.PHONY : src/graphics.o

# target to build an object file
src/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/graphics.cpp.o
.PHONY : src/graphics.cpp.o

src/graphics.i: src/graphics.cpp.i

.PHONY : src/graphics.i

# target to preprocess a source file
src/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/graphics.cpp.i
.PHONY : src/graphics.cpp.i

src/graphics.s: src/graphics.cpp.s

.PHONY : src/graphics.s

# target to generate assembly for a file
src/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/graphics.cpp.s
.PHONY : src/graphics.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/lua.o: src/lua.cpp.o

.PHONY : src/lua.o

# target to build an object file
src/lua.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/lua.cpp.o
.PHONY : src/lua.cpp.o

src/lua.i: src/lua.cpp.i

.PHONY : src/lua.i

# target to preprocess a source file
src/lua.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/lua.cpp.i
.PHONY : src/lua.cpp.i

src/lua.s: src/lua.cpp.s

.PHONY : src/lua.s

# target to generate assembly for a file
src/lua.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/lua.cpp.s
.PHONY : src/lua.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/physics.o: src/physics.cpp.o

.PHONY : src/physics.o

# target to build an object file
src/physics.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/physics.cpp.o
.PHONY : src/physics.cpp.o

src/physics.i: src/physics.cpp.i

.PHONY : src/physics.i

# target to preprocess a source file
src/physics.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/physics.cpp.i
.PHONY : src/physics.cpp.i

src/physics.s: src/physics.cpp.s

.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/physics.cpp.s
.PHONY : src/physics.cpp.s

src/shaders.o: src/shaders.cpp.o

.PHONY : src/shaders.o

# target to build an object file
src/shaders.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/shaders.cpp.o
.PHONY : src/shaders.cpp.o

src/shaders.i: src/shaders.cpp.i

.PHONY : src/shaders.i

# target to preprocess a source file
src/shaders.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/shaders.cpp.i
.PHONY : src/shaders.cpp.i

src/shaders.s: src/shaders.cpp.s

.PHONY : src/shaders.s

# target to generate assembly for a file
src/shaders.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/shaders.cpp.s
.PHONY : src/shaders.cpp.s

src/tsab.o: src/tsab.cpp.o

.PHONY : src/tsab.o

# target to build an object file
src/tsab.cpp.o:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/tsab.cpp.o
.PHONY : src/tsab.cpp.o

src/tsab.i: src/tsab.cpp.i

.PHONY : src/tsab.i

# target to preprocess a source file
src/tsab.cpp.i:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/tsab.cpp.i
.PHONY : src/tsab.cpp.i

src/tsab.s: src/tsab.cpp.s

.PHONY : src/tsab.s

# target to generate assembly for a file
src/tsab.cpp.s:
	$(MAKE) -f CMakeFiles/tsab.dir/build.make CMakeFiles/tsab.dir/src/tsab.cpp.s
.PHONY : src/tsab.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tsab"
	@echo "... src/audio.o"
	@echo "... src/audio.i"
	@echo "... src/audio.s"
	@echo "... src/fs.o"
	@echo "... src/fs.i"
	@echo "... src/fs.s"
	@echo "... src/graphics.o"
	@echo "... src/graphics.i"
	@echo "... src/graphics.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/lua.o"
	@echo "... src/lua.i"
	@echo "... src/lua.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/physics.o"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
	@echo "... src/shaders.o"
	@echo "... src/shaders.i"
	@echo "... src/shaders.s"
	@echo "... src/tsab.o"
	@echo "... src/tsab.i"
	@echo "... src/tsab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

